version: '3'
services:
  api:
    image: node:16.15.0
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run start"
